### ISSUE TITLE
Hackalist ping endpoint support

### ISSUE THREAD

**Issue by bholagabbar** [wolfbeacon/wolfbeacon-nginx-router#2]
https://github.com/wolfbeacon/wolfbeacon-nginx-server/blob/master/nginx.vh.default.example.conf#L6 
routes it to /hackalist/hackathons . There's also /hackalist/ping . Need to write config for that @junthehacker

**Comment by junzhengca** [comment]
Fixed by pull request [#5](https://github.com/wolfbeacon/wolfbeacon-nginx-router/pull/5)
